version: '3'
services:
  nuxt-starter:
    image: nomadventrs/nuxt-starter
    build: 
      context: .
    ports:
      - "3010:3010"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      HOST: 0.0.0.0